[tool.poetry]
name = "py_lister"
version = "0.1.0"
description = ""
authors = ["Tobias Schmitt <tobias.schmitt2009@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
